import type { Metadata } from "next";
import {Plus_Jakarta_Sans } from "next/font/google";
import LenisScrollProvider from "./_provider/LenisProvider";
import "./globals.css";

const jakartatSans = Plus_Jakarta_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prime Up LLC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartatSans.variable} antialiased`}
      >
        <LenisScrollProvider>
          {children}
        </LenisScrollProvider>
      </body>
    </html>
  );
}
